Digital_Aristotle/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('chatbot/', include(('apps.chatbot.urls', 'apps.chatbot'), namespace='chatbot')),
    path('admin_area/', include(('apps.admin_area.urls', 'apps.admin_area'), namespace='admin_area')),
    path('admin/', admin.site.urls),
]

apps/admin_area/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload')
]

apps/chatbot/urls.py
from django.urls import path

from .views import index, get_response

urlpatterns = [
    path('', index, name='index'),
    path('get-response/', get_response, name='get_response'),
]

apps/admin_area/forms.py
# Simple form for users to upload files to the server

from django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

apps/admin_area/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UploadFileForm
from .handle_upload import handle_uploaded_file


@login_required(login_url='/accounts/login/')
def index(request, template_name="admin_area/index.html"):
    context = {'title': 'Digital Aristotle'}
    return render(request, template_name, context)


@login_required(login_url='/accounts/login/')
def upload(request, template_name="admin_area/upload.html"):
    context = {'title': 'Digital Aristotle'}

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        handle_uploaded_file(request.FILES['file'], request.FILES['file'].name, request.FILES['file'].content_type)

    else:
        form = UploadFileForm()

    return render(request, template_name, {'form': form})

apps/chatbot/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def get_response(request):
    response = {'status': None}

    if request.method == 'POST':
        data = json.loads(request.body)
        message = data['message']

        chat_response = 'ok'  # to be replaced later with a function
        response['message'] = {'text': chat_response, 'user': False, 'chat_bot': True}
        response['status'] = 'ok'

    else:
        response['error'] = 'no post data found'

    return HttpResponse(
        json.dumps(response),
        content_type="application/json"
    )


def index(request, template_name="chatbot/index.html"):
    context = {'title': 'Digital Aristotle'}
    return render(request, template_name, context)

chatbot/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Index page successfully accessed.")

apps/admin_area/templates/admin_area/index.html
{% extends 'base.html' %}

{% block content %}

    <body>
        <div class = "admin-area-page">
            <div class="admin-area">
                <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
                    <div class="container"><a class="navbar-brand">Digital Aristotle</a><a class="btn btn-light action-button" role="button" href="{% url 'logout' %}">Logout</a></div>
                </nav>
                <div class="container hero">
                    <div class="row">
                    <div class="col-12 col-lg-6 col-xl-5 offset-xl-1"><a class="btn btn-light action-button" role="button" href="{% url 'admin_area:upload' %}">Upload to Chatbot's brain</a></div>
                </div>
                <div class="row">
                    <div class="col-12 col-lg-6 col-xl-5 offset-xl-1"><a class="btn btn-light action-button" role="button" href="{% url 'admin:index' %}" style="margin-top: 50px;">Manage Users</a></div>
                </div>
                </div>
            </div>
        </div>
    </body>

{% endblock content %}

apps/admin_area/templates/admin_area/upload.html
{% extends 'base.html' %}

{% block content %}

    <body>
        <div>
            <div class="admin-area">
                <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
                    <div class="container"><a class="navbar-brand">Digital Aristotle</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse"
                            id="navcol-1">
                            <ul class="nav navbar-nav">
                                <li class="nav-item" role="presentation"></li>
                            </ul>
                            <form class="form-inline mr-auto" target="_self">
                                <div class="form-group"><label for="search-field"></label></div>
                            </form><a class="btn btn-light action-button" role="button" href="{% url 'admin_area:index' %}" style="margin-right: 10px;">Go back</a><a class="btn btn-light action-button" role="button" href="{% url 'logout' %}">Logout</a><span class="navbar-text"> </span></div>
                    </div>
                </nav>
                <div class="container hero">
                    <div class="row">
                        <div class="col-12 col-lg-6 col-xl-5 offset-xl-1">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="file" name="file">
                                <button type="submit">Upload</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>

{% endblock content %}

apps/admin_area/templates/admin_index.html
{% extends 'base.html' %}

apps/chatbot/templates/chatbot/index.html
{% extends 'base.html' %}

{% load static %}

{% block js %}

    <script src={% static 'js/chatbot-messaging.js' %}></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-chat-scroll/dist/vue-chat-scroll.min.js"></script>

{% endblock %}

{% block content %}

    <div class = "chatbot">
        <nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">
            <div class="container"><a class="navbar-brand">Digital Aristotle</a></div>
        </nav>
        <div id="conversation" class="container">

            <div id="responses" v-chat-scroll>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card col-md-6 responsesBackground" v-for="message in messages"
                             v-bind:class="{ 'user-message': message.user,  'chat-message': message.chat_bot, 'offset-md-6': message.chat_bot}">
                            <div class="card-body">
                                [[message.text]]
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="input">
                <div class="col-md-12">
                    <textarea
                            name = "textarea" class="form-control" v-bind:placeholder="placeholder" v-model="input"
                            v-bind:class="{ 'border-danger': send_blank}" v-on:change="check_content" v-on:keyup.enter="add_message">
                    </textarea>
                </div>
            </div>

        </div>

    </div>


{% endblock %}

apps/chatbot/templates/chatbot_index.html
{% extends 'base.html' %}

{% load static %}

{% block js %}

  <script src={% static 'chatbot/js/script.js' %}></script>

{% endblock %}

{% block content %}

  <div id="conversation" class="container top-padding">

    <div id="responses">
        <div class="row">
            <div class="col-md-12">
                <div class="card col-md-6" v-for="message in messages" v-bind:class="{ 'user-message': message.user,  'chat-message': message.chat_bot, 'offset-md-6': message.chat_bot}">
                    <div class="card-body">
                        [[message.text]]
                    </div>
                </div>
            </div>
        </div>
    </div>

  	<div id="input">
  		<div class="col-md-12">
  			<textarea class="form-control" v-bind:placeholder="placeholder" v-model="input" v-bind:class="{ 'border-danger': send_blank}" v-on:change="check_content" v-on:keyup.enter="add_message"></textarea>
  		</div>
  	</div>

  </div>

{% endblock %}

chatbot/templates/index.html
!DOCTYPE html>

<html>

    <!-- Head section -->
	<head>

		<link href="/css/bootstrap.min.css" rel="stylesheet"/>
		<link href="/css/bootstrap-theme.min.css" rel="stylesheet"/>
		<link href="/css/styles.css" rel="stylesheet"/> <!-- Main CSS file -->
        <link rel="icon" href="/img/favicon.ico?" type="image/x-icon">

        <meta charset="UTF-8">
        <title>Swansea University Chatbot</title>

        <!-- After the page is refreshed or a message is sent, focus will remain on the input box -->
        <script>
            document.getElementById(window.name==='reload'?'reload':'say').focus();
            window.name='reload';
        </script>

	</head>

    <!-- Body section-->
    <body onload="document.getElementById('say').focus()">

        <!-- Container which displays the conversation history -->
        <div id="responses">
            <?php echo $display . '<div id="end">&nbsp;</div>' . PHP_EOL ?>
        </div>
        <?php echo $debug_div ?>

        <!-- Input box. The user can send information to the chatbot from here -->
        <form name="chatform" method="post" action="index.php#end"
            onsubmit="if(document.getElementById('say').value == '') return false;">

            <!-- Sends the user message, the conversation ID and the bot's ID to the SQL database -->
            <div id="input">
                <label for="say">Say:</label>
                <input type="text" name="say" id="say" size="70"/>
                <input type="submit" name="submit" id="btn_say" value="say"/>
                <input type="hidden" name="convo_id" id="convo_id" value="<?php echo $convo_id; ?>"/>
                <input type="hidden" name="bot_id" id="bot_id" value="<?php echo $bot_id; ?>"/>
                <input type="hidden" name="format" id="format" value="<?php echo $format; ?>"/>
            </div>

        </form>

        <!--
        The user can use this to refresh the page and, thus, clear the display of the conversation history.
        There is one issue with this feature: a new conversation ID and log will be created by refreshing the page.
        -->
        <div id="clearhistory">
            <a href="index.php"> Clear conversation history </a>
        </div>

    <!-- Copyright notice -->
    <div id="bottom">
	    Copyright &#169; 2018 Ghiuzan Gabriel<br>All rights reserved.
    </div>


</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>{% block title %} {{ title }} {% endblock %}</title>
        <meta name="description" content="Chatbot for students">
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
        <link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'fonts/ionicons.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'css/login.css' %}" rel="stylesheet"/>
        <link href="{% static 'css/admin-area.css' %}" rel="stylesheet"/>
        <link href="{% static 'css/chatbot-messaging.css' %}" rel="stylesheet"/>

        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src={% static 'js/jquery.min.js' %}></script>
        <script src={% static 'bootstrap/js/bootstrap.min.js' %}></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src={% static 'js/new-age.js' %}></script>


        {% block css %} {% endblock %}

	    {% block js %} {% endblock %}

	</head>
{% block content %} {% endblock content %}
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<body id="page-top">
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container"><a class="navbar-brand js-scroll-trigger" href="#page-top">Digital Aristotle</a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler float-right" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
            <div
                class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                </ul>
        </div>
        </div>
    </nav>
    <header class="masthead" style="background:url({% static 'img/bg-pattern.png' %}), linear-gradient(to left, #7b4397, #dc2430);height:100%;">
        <div class="container h-100">
            <div class="row h-100">
                <div class="col-lg-7 col-xl-12 my-auto" style="width: 667px;margin: 0px;">
                    <div class="mx-auto header-content">
                        <h1 class="text-center mb-5" style="font-size: 40px;">Welcome to Digital Aristotle! Your University's new learning assistant</h1>
                    </div>
                    <div class="mx-auto header-content">
                        <h1 class="text-center mb-5" style="font-size: 40px;">Who are you?</h1><a class="btn btn-outline-warning float-left btn-xl js-scroll-trigger" role="button" href="{% url 'chatbot:index' %}">Student</a><a class="btn btn-outline-warning float-right btn-xl js-scroll-trigger" role="button" href="{% url 'admin_area:index' %}">Admin</a></div>
                </div>
            </div>
        </div>
    </header>
    <footer>
        <div class="container">
            <p>©&nbsp;Digital Aristotle 2019. All Rights Reserved.</p>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Privacy</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">FAQ</a></li>
            </ul>
        </div>
    </footer>
</body>

{% endblock content %}